[package]
name = "dict-build"
version.workspace = true
edition.workspace = true

[dependencies]
dict-core = { path = "../dict-core" }
anyhow.workspace = true
flate2 = "1.1.10"
bzip2-rs = "0.1.2"

[[bin]]
name = "dict-build"
path = "src/main.rs"

[[bin]]
name = "dict-query"
path = "src/bin/query.rs"

[lints]
workspace = true
